# domain:       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
# url:          # the base hostname and protocol for your site, e.g. http://example.com
# baseurl:      # place folder name if the site is served in a subfolder

title: My minimal minima
author:
  name: Author Name
  email: your-email@domain.com


# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
    Write an awesome description for your new site here.
  
# This was the original site description. I shortened it to make the footer smaller.
#
# Write an awesome description for your new site here. You can edit this line
# in _config.yml. It will appear in your document head meta (for Google search
# results) and in your feed.xml site description.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# To toggle the rss feed in the footer, comment or uncomment below
enable_footer_feed: true


# Disqus Comments
# Leave shortname blank to disable comments site-wide.
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
disqus:
  shortname:
# Disqus needs this to work. It needs to be `https://mysite.github.io` or whatever the disqus is set to.
# url: https://mysite.github.io

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md
  - posts.md
  - tags.html
  - author.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%Y-%m-%d"

  # Generate social links in footer.
# social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# Changes the output directory for the build. Default is _site
destination: dist

# Add Google analytics - add your analytics code and uncomment
# google_analytics: UA-XXXXXXXX-X